Fixed bug where "stump_parameter_id" was not used and the wrong ID was used instead
This would cause the following exception:
IntegrityError: FOREIGN KEY constraint failed
in in _populate_admin_boundaries(self) line 127